name: ParticleNativeAPI
version: ${project.version}
main: com.github.xap3y.particlenativeapi.plugin.ParticleNativePlugin

author: Fierioziy
description: "Provides API for spawning particles."

load: STARTUP
api-version: "1.13"